#!/usr/bin/env node
// preflight.mjs — THE 3r4l ACCEPTANCE, fail-closed (FILM-SPEC.md §ACCEPTANCE (a)–(h) + the studio's B and C re-implemented against the 3r4l masters;
// the studio's own preflight.py A–F cannot run on a non-KJ film and is SKIPPED by design — its ledger says so). Every number lands in ledger.json;
// MASTERS.sha256 is written over the masters first and its own hash is carried in the ledger. A frame grab at every beat (the 9:16) and the end
// card (both) go to the scratch dir. rc 1 on any FAIL. Usage: node film/preflight.mjs <masters-dir> <scratch-dir> [--pad A|B] [--pad-spend-usd N] [--pad-note "…"]
import { execFileSync, spawnSync } from 'node:child_process'; import { createHash } from 'node:crypto'; import fs from 'node:fs'; import path from 'node:path';
import { chromium } from '@playwright/test'; import http from 'node:http'; import { normalise } from '../normalise.mjs'; import { frameMeans } from './mux.mjs';
const R = path.resolve(path.dirname(new URL(import.meta.url).pathname)), SITE = path.resolve(R, '..'), [,, M, SCR] = process.argv; if (!M || !SCR) { console.error('usage: node film/preflight.mjs <masters-dir> <scratch-dir> [--pad A|B]'); process.exit(2); }
const argv = process.argv.slice(4), opt = k => argv.includes(k) ? argv[argv.indexOf(k) + 1] : null, PAD = opt('--pad') || 'B', PAD_SPEND = +(opt('--pad-spend-usd') || 0), PAD_NOTE = opt('--pad-note') || '', WORK = opt('--work');
const FF = '/opt/homebrew/bin/ffmpeg', FP = '/opt/homebrew/bin/ffprobe', J = p => JSON.parse(fs.readFileSync(p, 'utf8')), sha = f => createHash('sha256').update(fs.readFileSync(f)).digest('hex'), shaStr = s => createHash('sha256').update(s).digest('hex');
const job = path.join(R, 'job'), plan = J(path.join(job, 'plan.json')), beats = J(path.join(job, 'beats.json')), lines = J(path.join(job, 'lines.json')), studio = J(path.join(job, 'ledger.json')), work = WORK || path.join(M, 'work'), mux = J(path.join(M, 'mux.json'));
const recL = J(path.join(work, 'rec-1920x1080.json')), recP = J(path.join(work, 'rec-1080x1920.json')), trim = J(path.join(path.dirname(plan.segments_dir.replace(/^~\//, process.env.HOME + '/')), 'trimmed', 'trim-report.json'));
const land = path.join(M, 'card-1080.mp4'), fwd = path.join(M, 'card-720.mp4'), port = path.join(M, 'card-9x16-1080.mp4'), p720 = path.join(M, 'card-9x16-720.mp4'), vtt = path.join(M, 'card.vtt'), INTRO = plan.intro_ms / 1000;
const ffErr = a => spawnSync(FF, ['-hide_banner', ...a, '-f', 'null', '-'], { encoding: 'utf8', maxBuffer: 1 << 26 }).stderr, dur = f => parseFloat(execFileSync(FP, ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', f]));
const silencesOf = (f, noise, d) => { const e = ffErr(['-i', f, '-af', `silencedetect=noise=${noise}:d=${d}`]); const s = [...e.matchAll(/silence_start: ([\d.]+)/g)].map(m => +m[1]), en = [...e.matchAll(/silence_end: ([\d.]+)/g)].map(m => +m[1]); return s.map((x, i) => ({ start: x, end: en[i] ?? null })); };
const rmsDbAt = (f, start, len = 1.0) => { const raw = spawnSync(FF, ['-v', 'error', '-ss', String(start), '-t', String(len), '-i', f, '-f', 's16le', '-ac', '1', '-ar', '8000', '-'], { maxBuffer: 1 << 24 }).stdout; const n = raw.length >> 1; if (!n) return -120; let s = 0; for (let i = 0; i < n; i++) { const v = raw.readInt16LE(i * 2) / 32768; s += v * v; } const r = Math.sqrt(s / n); return r > 1e-6 ? 20 * Math.log10(r) : -120; };
const rows = [], row = (key, name, ok, got, want, extra = {}) => { rows.push({ key, name, ok: !!ok, got, want, ...extra }); console.log(`  [${ok ? 'PASS' : 'FAIL'}] (${key}) ${name} — ${typeof got === 'object' ? JSON.stringify(got) : got} (want ${want})`); return ok; };
fs.mkdirSync(path.join(SCR, 'frames'), { recursive: true });
const card = fs.readFileSync(path.join(SITE, 'content', 'card.txt'), 'utf8'), cardLines = [...card.matchAll(/^== \w+ ==\n([\s\S]*?)(?=\n== \w+ ==\n|(?![\s\S]))/gm)].flatMap(m => m[1].replace(/\n$/, '').split('\n'));
// (a) the VTT's cues joined and normalised == card.txt normalised, WHOLE
const cues = fs.readFileSync(vtt, 'utf8').split(/\n\n+/).filter(b => /-->/.test(b)).map(b => b.split('\n').filter(l => l && !/-->/.test(l) && !/^\d+$/.test(l)).join(' '));
const aVtt = normalise(cues.join(' ')), aCard = normalise(cardLines.join(' ')); row('a', 'VTT cues joined == card.txt whole (normalised)', aVtt === aCard, `${cues.length} cues, ${aVtt.length} chars`, `${cardLines.length} card lines, ${aCard.length} chars`);
// (b) whisper large-v3-turbo on the master ≤ 0.5 % WER vs card.txt (+ the spoken credit) after the aloud normalisation, every line present
const NUM = { 0: 'zero', 1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five', 6: 'six', 7: 'seven', 8: 'eight', 9: 'nine' };
const norm = s => s.toLowerCase().replace(/3r4l\.org/g, ' three r four l dot org ').replace(/\b3\s*r\s*4\s*l\b/g, ' three r four l ').replace(/\.org\b/g, ' dot org ').replace(/\d/g, d => ` ${NUM[d]} `).replace(/every\s+day/g, 'everyday').replace(/some\s+day/g, 'someday').replace(/[’']/g, '').replace(/[^a-z\s]+/g, ' ').trim().split(/\s+/).filter(Boolean);
// THE DECODE OF RECORD: turbo in windows cut at the composed silences (the Prayer Room law, handoffs/2026-10-03-prayer-room-voice-FINISH-HANDOFF.md:109 —
// a whole-file turbo pass lost "When we can't do" and doubled "I understand I am a sinner" on this very film, 2026-10-08; --max-context 0 still lost the four words).
// Each window opens 0.3 s before a line whose composed pre-gap is ≥ 1.0 s, so every cut lands in silence. The whole-file read is kept beside it in the ledger.
const wav = path.join(SCR, 'whisper-16k.wav'), WH = '/opt/homebrew/bin/whisper-cli', MODEL = path.join(process.env.HOME, 'whisper-models', 'ggml-large-v3-turbo.bin'); execFileSync(FF, ['-y', '-loglevel', 'error', '-i', land, '-vn', '-ac', '1', '-ar', '16000', '-c:a', 'pcm_s16le', wav]);
const whisper = (f, base) => { execFileSync(WH, ['-m', MODEL, '-f', f, '-l', 'en', '-otxt', '-of', base, '-np', '-nt'], { stdio: 'ignore' }); return fs.readFileSync(base + '.txt', 'utf8').trim(); };
const wholeFile = whisper(wav, path.join(SCR, 'whisper-whole')), cutsAt = [0, ...lines.filter(l => l.pre_s >= 1.0 && l.name !== 'title').map(l => +(INTRO + beats.beats_s[+l.beat.slice(1) - 1] + l.lead_s - 0.3).toFixed(3)), dur(wav)];
const windows = cutsAt.slice(0, -1).map((s, i) => { const w = path.join(SCR, `whisper-w${String(i).padStart(2, '0')}.wav`); execFileSync(FF, ['-y', '-loglevel', 'error', '-ss', String(s), '-t', String(+(cutsAt[i + 1] - s).toFixed(3)), '-i', wav, w]); return { from_s: s, to_s: cutsAt[i + 1], text: whisper(w, w.replace(/\.wav$/, '')) }; });
fs.writeFileSync(path.join(SCR, 'whisper-chunked.txt'), windows.map(w => w.text).join('\n') + '\n');
const hyp = norm(windows.map(w => w.text).join(' ')), hypWhole = norm(wholeFile), creditLine = lines.find(l => l.block === 'credit').card, refCard = norm(cardLines.join(' ')), ref = refCard.concat(norm(creditLine));
function align(r, h) { const n = r.length, m = h.length, D = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0)); for (let i = 0; i <= n; i++) D[i][0] = i; for (let j = 0; j <= m; j++) D[0][j] = j;
  for (let i = 1; i <= n; i++) for (let j = 1; j <= m; j++) D[i][j] = Math.min(D[i - 1][j] + 1, D[i][j - 1] + 1, D[i - 1][j - 1] + (r[i - 1] === h[j - 1] ? 0 : 1));
  const errs = []; let i = n, j = m; while (i > 0 || j > 0) { if (i > 0 && j > 0 && D[i][j] === D[i - 1][j - 1] + (r[i - 1] === h[j - 1] ? 0 : 1)) { if (r[i - 1] !== h[j - 1]) errs.push({ at: i - 1, sub: [r[i - 1], h[j - 1]] }); i--; j--; } else if (i > 0 && D[i][j] === D[i - 1][j] + 1) { errs.push({ at: i - 1, del: r[i - 1] }); i--; } else { errs.push({ at: i, ins: h[j - 1] }); j--; } } return errs.reverse(); }
const errs = align(ref, hyp), cardErrs = errs.filter(e => e.at < refCard.length), wer = cardErrs.length / refCard.length;
const missing = cardLines.filter(l => { const t = norm(l); if (!t.length) return false; let best = Infinity; for (let j = 0; j + t.length <= hyp.length; j++) { let d = 0; for (let k = 0; k < t.length && d <= 1; k++) if (t[k] !== hyp[j + k]) d++; best = Math.min(best, d); } return best > 1; });
const wholeErrs = align(ref, hypWhole).filter(e => e.at < refCard.length);
row('b', 'whisper large-v3-turbo WER on the card words (windows at the composed silences)', wer <= 0.005 && missing.length === 0, `${cardErrs.length} of ${refCard.length} words = ${(wer * 100).toFixed(2)} %, ${missing.length} line(s) missing; the whole-file read beside it: ${wholeErrs.length} errors`, '≤ 0.5 %, every line present',
  { method: 'ggml-large-v3-turbo, -l en, windows cut 0.3 s before every line with a composed pre-gap ≥ 1.0 s', windows: windows.map(w => ({ from_s: w.from_s, to_s: w.to_s, words: norm(w.text).length })), card_errors: cardErrs, credit_errors: errs.filter(e => e.at >= refCard.length), missing_lines: missing, hyp_words: hyp.length, whole_file_read: { errors_on_card: wholeErrs, note: 'the whole-file turbo pass is NOT the gate: it drops and doubles words on long reads (the Prayer Room trap)' } });
// (c) tail-RMS < 0.015 per take; no unplanned gap > 1.4 s (a silence that starts inside a take's own speech, or runs past its composed pre-gap)
const segDir = plan.segments_dir.replace(/^~\//, process.env.HOME + '/'), tails = Object.entries(trim.segments).map(([f, r]) => ({ f, rms: r.tail_rms, ok: r.tail_ok })), tl = []; let t = 0;
for (const s of plan.assembly.segments) { const f = s.seg + '.mp3', d = trim.segments[f].out_s, tail = trim.segments[f].cut_at_s ? trim.keep_s : trim.segments[f].trailing_silence_s; t += s.pre_s; tl.push({ seg: s.seg, start: t, speech_end: t + d - tail, end: t + d, pre_s: s.pre_s }); t += d; }
// a PLANNED gap begins within 0.4 s of the previous take's cut point (the composed pre-gap + the keep + the take's own release) and ends within 0.25 s after the next line's file start (a soft onset — an F, an S, an H — crosses the −40 dB floor 100–200 ms into its take: the "For continuous help" line crossed it at 126 ms, measured 2026-10-08)
const narr = path.join(work, 'narration-full.wav'), sil = silencesOf(narr, '-40dB', 1.4), unplanned = sil.filter(g => { if (g.end === null || g.end > beats.total_s - plan.assembly.tail_s + 0.1) return false; const k = tl.find(x => g.start >= x.start - 0.1 && g.start < x.end + 0.1); if (!k) return true; const next = tl[tl.indexOf(k) + 1]; return !(g.start >= k.speech_end - 0.4 && (!next || g.end <= next.start + 0.25)); }).map(g => ({ ...g, len: +(g.end - g.start).toFixed(2) }));
const internal = plan.assembly.segments.flatMap(s => silencesOf(path.join(segDir, s.seg + '.mp3'), '-38dB', 1.4).filter(g => g.end !== null).map(g => ({ seg: s.seg, ...g })));
row('c', 'tail-RMS < 0.015 per take', tails.every(x => x.ok), `max ${Math.max(...tails.map(x => x.rms)).toFixed(4)} over ${tails.length} takes`, '< 0.015'); row('c', 'no unplanned gap > 1.4 s', unplanned.length === 0 && internal.length === 0, `${unplanned.length} in the narration, ${internal.length} inside a take`, 0, { unplanned, internal, gaps_over_1_4_s: sil.filter(g => g.end !== null).map(g => ({ ...g, len: +(g.end - g.start).toFixed(2), planned: !unplanned.some(u => u.start === g.start) })), rule: 'planned = begins within 0.4 s of the previous take\'s cut point (pre-gap + keep + release) and ends within 0.25 s after the next take\'s file start (a soft onset); the tail after the last line is the composed tail_s' });
// (d) duration 1:45–2:30
const D = dur(land); row('d', 'master duration', D >= 105 && D <= 150, `${D.toFixed(2)} s = ${Math.floor(D / 60)}:${(D % 60).toFixed(1).padStart(4, '0')}`, '105–150 s');
// (e) LUFS −17.8 ± 1, TP ≤ −1.5, the outro measured (the studio's C)
const eb = ffErr(['-i', land, '-af', 'ebur128=peak=true']), I = +(/\n\s+I:\s+(-?[\d.]+) LUFS/.exec(eb) || [])[1], TP = +(/Peak:\s+(-?[\d.]+) dBFS/.exec(eb) || [])[1], speechEnd = INTRO + beats.total_s - plan.assembly.tail_s;
const bedAlone = rmsDbAt(land, speechEnd + 0.5), finalSec = rmsDbAt(land, D - 1.0);
row('e', 'integrated loudness', Math.abs(I - plan.mix.target_lufs) <= 1, `${I} LUFS`, `${plan.mix.target_lufs} ± 1`); row('e', 'true peak', TP <= -1.5, `${TP} dBTP`, '≤ −1.5'); row('e', 'outro: final second', finalSec < -45, `${finalSec.toFixed(1)} dBFS`, '< −45');
row('e', PAD === 'A' ? 'outro: bed alone after speech' : 'outro: bed alone after speech (n/a — pad B, the silent bed; recorded, not gated)', PAD === 'A' ? bedAlone > -55 : true, `${bedAlone.toFixed(1)} dBFS`, PAD === 'A' ? '> −55' : 'n/a');
// (f) median f0 100–106 Hz (librosa pyin over the voiced frames of the narration)
// the Audio Bible's own recipe (qa.py:392–399 on origin/audio-bible/main): 22.05 kHz, a 60 s window from 10 s, pyin 60–300 Hz, frame 2048, the voiced frames' median; the whole narration beside it
const f0r = JSON.parse(execFileSync('python3', ['-c', `import librosa,numpy as np,sys,json\np=sys.argv[1];d=librosa.get_duration(path=p);o=10.0 if d>75 else 0.0\ny,sr=librosa.load(p,sr=22050,mono=True,offset=o,duration=60.0);f,v,_=librosa.pyin(y,fmin=60,fmax=300,sr=sr,frame_length=2048);f=f[np.isfinite(f)&v];m=float(np.median(f))\ny2,sr=librosa.load(p,sr=22050,mono=True);f2,v2,_=librosa.pyin(y2,fmin=60,fmax=300,sr=sr,frame_length=2048);f2=f2[np.isfinite(f2)&v2]\nprint(json.dumps({'window_hz':round(m,2),'window_sd_st':round(float(np.std(12*np.log2(f/m))),3),'window_s':[o,60],'whole_hz':round(float(np.median(f2)),2),'voiced_frames':int(f2.size)}))`, narr], { encoding: 'utf8' }).trim());
const REF_HZ = 105.7, driftSt = +(12 * Math.log2(f0r.whole_hz / REF_HZ)).toFixed(2), f0 = f0r.whole_hz; // voice.json register.median_f0_hz_first_chunk (the pinned reference); the runbook's own pinned line read 110.8 Hz
row('f', 'median f0 (the spec\'s band; the pinned settings sha in the ledger)', f0 >= 100 && f0 <= 106, `${f0.toFixed(1)} Hz whole narration · ${f0r.window_hz} Hz in the Audio Bible\'s 60 s window · ${driftSt} st from the pinned reference ${REF_HZ} Hz (the Audio Bible\'s drift gate ≤ 1.5 st: ${Math.abs(driftSt) <= 1.5 ? 'PASS' : 'FAIL'})`, '100–106 Hz', { ...f0r, reference_hz: REF_HZ, drift_semitones: driftSt, runbook_pinned_line_hz: 110.8 });
// (g) legibility at 390×844 on the 9:16 (the DOM at every beat, font-size × 390/1080 ≥ 13 px), fonts.check at the first beat frame, the A/V onset ≤ 80 ms
const built = fs.readFileSync(path.join(R, 'build', 'card.html')), srv = http.createServer((q, r) => { r.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); r.end(built); }).listen(0, '127.0.0.1'); await new Promise(r => srv.on('listening', r));
const browser = await chromium.launch(), ctx = await browser.newContext({ viewport: { width: 1080, height: 1920 }, colorScheme: 'light' }), page = await ctx.newPage(); await page.goto(`http://127.0.0.1:${srv.address().port}/card.html`, { waitUntil: 'networkidle' });
const legib = []; for (let k = 0; k < beats.beats_s.length; k++) { await page.evaluate(ms => window.__seek(ms), Math.round(beats.beats_s[k] * 1000) + 60); await page.waitForTimeout(1500);
  const m = await page.evaluate(() => [...document.querySelectorAll('.speak.spoken, .wordmark, .credit')].filter(e => getComputedStyle(e).opacity !== '0' && e.getBoundingClientRect().width > 0).map(e => ({ cls: e.className, px: parseFloat(getComputedStyle(e).fontSize), text: e.textContent.slice(0, 24) })));
  const min = m.length ? Math.min(...m.map(x => x.px)) : null; legib.push({ beat: k + 1, lines: m.length, min_px_1080: min, min_px_390: min === null ? null : +(min * 390 / 1080).toFixed(1) }); }
await browser.close(); srv.close(); const worst = legib.filter(x => x.min_px_390 !== null).reduce((a, b) => a.min_px_390 <= b.min_px_390 ? a : b);
row('g', 'every on-screen line ≥ 13 px at 390×844 on the 9:16', legib.every(x => x.min_px_390 === null || x.min_px_390 >= 13), `min ${worst.min_px_390} px (beat ${worst.beat}: ${worst.min_px_1080} px at 1080)`, '≥ 13', { per_beat: legib });
row('g', 'document.fonts.check(1em "Source Serif 4") at the first beat frame (both records)', recL.fonts_check_at_first_beat && recP.fonts_check_at_first_beat, `${recL.fonts_check_at_first_beat} / ${recP.fonts_check_at_first_beat}`, 'true');
// the spoken onset = the voice track's first sound + the mux's adelay (the narration is what the mux delays by exactly intro_ms); the master's own first sound is kept beside it — under a pad it is the bed's fade-in, not the voice (caught 2026-10-08: 1.742 s vs the voice at 2.477)
const onsetA = +(INTRO + silencesOf(narr, '-40dB', 0.4)[0]?.end).toFixed(3), firstSound = silencesOf(land, '-40dB', 0.4)[0]?.end, fm = frameMeans(land, recL.rects.title, ['-t', '6']), win = fm.filter(x => x.t >= INTRO - 0.1 && x.t <= INTRO + 1.2), peak = win.reduce((a, b) => a.mean >= b.mean ? a : b), litFrame = fm.find(x => x.t > peak.t && x.mean <= peak.mean - 3), onsetV = litFrame ? litFrame.t : null;
row('g', 'A/V onset: the first spoken onset vs the first .spoken frame', onsetV !== null && Math.abs(onsetV - onsetA) <= 0.08, `voice ${onsetA.toFixed(3)} s (the narration's onset + ${plan.intro_ms} ms) · lit frame ${onsetV?.toFixed(3)} s · Δ ${onsetV === null ? 'n/a' : Math.round((onsetV - onsetA) * 1000) + ' ms'} · the master's first sound ${firstSound?.toFixed(3)} s`, '≤ 80 ms', { planned_onset_s: +(INTRO + beats.beats_s[0]).toFixed(3), master_first_sound_s: firstSound });
// (h) no external request in the film file; the 720 ≤ 10 MB target, ≤ 25 MB refusal
const html = built.toString(), ext = /(src|href)\s*=\s*["']?\s*(https?:)?\/\//i.test(html) || /url\((?!\s*["']?data:)/i.test(html) || /@import|fetch\(|XMLHttpRequest|<link\b|<img\b|<iframe\b|<script\b[^>]*src=/i.test(html);
const stray = [...recL.requests, ...recP.requests].filter(u => u.split('#')[0] !== recL.url && u.split('#')[0] !== recP.url);
row('h', 'no external request in the film file', !ext && stray.length === 0, `${recL.requests.length + recP.requests.length} request(s) at the two records, ${stray.length} off the document; ${ext ? 'an external reference in the built html' : 'the built html self-contained'}`, 'the one document only');
const fwdMB = fs.statSync(fwd).size / 1e6; row('h', 'the 720 forward ≤ 10 MB target (25 MB refusal)', fwdMB <= 25, `${fwdMB.toFixed(2)} MB${fwdMB > 10 ? ' (over the 10 MB target)' : ''}`, '≤ 10 MB');
// frame grabs: every beat on the 9:16 (0.9 s into the beat) and the end card on both
for (let k = 0; k < beats.beats_s.length; k++) { const l = lines.find(x => +x.beat.slice(1) === k + 1), name = l ? l.name : (plan.assembly.extra_beats.find(x => x.beat === `b${k + 1}`) ? (k + 1 === +plan.assembly.extra_beats[0].beat.slice(1) ? 'turn' : 'end') : 'x');
  execFileSync(FF, ['-y', '-loglevel', 'error', '-ss', String((INTRO + beats.beats_s[k] + 0.9).toFixed(3)), '-i', port, '-frames:v', '1', path.join(SCR, 'frames', `9x16-beat-${String(k + 1).padStart(2, '0')}-${name}.png`)]); }
for (const [src, n] of [[port, '9x16'], [land, '16x9']]) execFileSync(FF, ['-y', '-loglevel', 'error', '-ss', String((D - 1.5).toFixed(3)), '-i', src, '-frames:v', '1', path.join(SCR, 'frames', `${n}-end-card.png`)]);
// MASTERS.sha256, then ledger.json
const masters = ['card-1080.mp4', 'card-720.mp4', 'card-9x16-1080.mp4', 'card-9x16-720.mp4', 'card.vtt', ...fs.readdirSync(path.join(M, 'cuts')).map(f => 'cuts/' + f)];
fs.writeFileSync(path.join(M, 'MASTERS.sha256'), masters.map(f => `${sha(path.join(M, f))}  ${f}`).join('\n') + '\n');
const fails = rows.filter(r => !r.ok), settingsSha = shaStr(JSON.stringify(plan.voice.settings)), prayerSettings = J(path.join(job, 'prayer-pass', 'plan.json')).voice.settings;
const ledger = { film: '3r4l-card', built_at: new Date().toISOString(), verdict: fails.length ? 'FAIL' : 'PASS', fails: fails.map(r => `(${r.key}) ${r.name}: ${typeof r.got === 'object' ? JSON.stringify(r.got) : r.got}`),
  source: { card_txt_sha256: shaStr(card), card_lines: cardLines.length, credit: creditLine, words_on_card: refCard.length }, meditate_rule: plan.meditate_rule,
  voice: { ...plan.voice, settings_sha256: settingsSha, prayer_pass: { settings: prayerSettings, settings_sha256: shaStr(JSON.stringify(prayerSettings)), beats: plan.pace.prayer_beats, note: PAD_NOTE ? undefined : undefined } },
  takes: { raw_dir: path.dirname(segDir), trimmed_dir: segDir, trailing_silence_removed_s: +Object.values(trim.segments).reduce((s, r) => s + r.in_s - r.out_s, 0).toFixed(2), keep_s: trim.keep_s, tts_report: J(path.join(path.dirname(segDir), 'tts-report.json')).segments },
  pad: { choice: PAD, bed: plan.bed, bed_sha256: studio.hashes.bed, bed_vol: plan.mix.bed_vol, spend_usd: PAD_SPEND, note: PAD === 'B' ? 'pad B: a generated silent bed (ffmpeg anullsrc) of the film\'s length — film-compile.mjs hashes the bed file, so it exists; the outro bed-alone gate is n/a' : PAD_NOTE },
  mix: { ...plan.mix, measured: { integrated_lufs: I, true_peak_dbtp: TP, final_second_dbfs: +finalSec.toFixed(1), bed_alone_after_speech_dbfs: +bedAlone.toFixed(1) } },
  studio_ledger: { ...studio, preflight_note: 'preflight: SKIPPED by design — the studio\'s gate A wants the KJ template\'s ids and ≥ 3 meditate lines (the rule the owner inverted for this film), gate D resolves tokens against kj-rebuild\'s globals.css, gate E reads a Postgres bundle row for the slug; none exist for this film (FILM-SPEC.md §chain 3). The 3r4l acceptance (a)–(h) below stands in its place.' },
  record: { poster_wait_ms: plan.intro_ms, mux_adelay_ms: mux.records['card-1080.mp4'].adelay_ms, note: 'the mux offset == the recorder\'s poster wait: the capture\'s head is cut at the real play frame so the master\'s poster is exactly 1600 ms', landscape: { clock: recL.clock, play_frame: mux.records['card-1080.mp4'].play_frame, head_cut_s: mux.records['card-1080.mp4'].head_cut_s }, portrait: { clock: recP.clock, play_frame: mux.records['card-9x16-1080.mp4'].play_frame, head_cut_s: mux.records['card-9x16-1080.mp4'].head_cut_s } },
  beats: { count: beats.beats_s.length, total_s: beats.total_s, beats_s: beats.beats_s, lines: lines.map(l => ({ beat: l.beat, name: l.name, block: l.block, pre_s: l.pre_s, lead_s: l.lead_s, speed: l.slow ? plan.pace.prayer_speed : plan.pace.default_speed })) },
  chapters: mux.chapters, masters: Object.fromEntries(masters.map(f => [f, { bytes: fs.statSync(path.join(M, f)).size, sha256: sha(path.join(M, f)) }])), masters_sha256_file: sha(path.join(M, 'MASTERS.sha256')), acceptance: rows, frames_dir: path.join(SCR, 'frames') };
fs.writeFileSync(path.join(M, 'ledger.json'), JSON.stringify(ledger, null, 1) + '\n');
console.log(`\nPREFLIGHT ${ledger.verdict} — ${fails.length} fail of ${rows.length} · ledger → ${path.join(M, 'ledger.json')} · MASTERS.sha256 over ${masters.length} files`); process.exit(fails.length ? 1 : 0);
